@startuml
(*) -->借阅证进行身份判断
if "系统判断借阅身份" then
-->[true]"身份验证通过"

if"系统验证所借图书状态" then
-->[true]"图书可借阅"

if"系统判断所借图书是否超标或存在逾期" then
-->[true]"未超标逾期"
-->"成功借阅"
-->"记录信息,修改可借数量"
-->"累加读者的借书数量"
-->(*)

else
-->[false]"存在超标逾期无法借阅"
-->(*)

endif

else
-->[false]"图书不可借阅"
--> (*)
endif

else
-->[false]"身份不符无法借阅"
-->(*)
endif
@enduml