@startuml
(*) -->读者登入系统
if "系统验证读者身份" then
-->[true]"读者查询图书状态"
-->"系统返回该图书状态"
-->"读者申请预约图书"
if "系统验证读者借书数量是否超标" then

if "图书不可借" then
-->[true]"提示用户该书不可预约"
-->(*)
else
if "预约人数超标" then
-->[true]"提示预约人数超标不可预约"
-->(*)
else
-->[false]"累加预约读者的数量"
-->" 系统更改图书状态，更新可预约书数量"
-->"更新用户可借(预约)书的的数量"

-->(*)
endif
endif
else
-->[false]"借书数量超标"
-->"还书"
-->"读者申请预约图书"
endif

else
-->[false]"系统提示读者身份和借书条件不符合"
-->(*)


endif
@enduml