@startuml
left to right direction
系统管理员 --> (图书管理)
(图书管理) .>(添加图书信息):<<include>>
(图书管理) ..>(查询图书信息):<<include>>
(图书管理) ..>(编辑图书信息):<<include>>
(图书管理) ..>(系统登录):<<include>>
系统管理员 --> (用户管理)
(用户管理) ..>(系统登录)
(用户管理) ..>(添加用户信息):<<include>>
(用户管理) ..>(编辑用户信息):<<include>>
(用户管理) ..>(查询用户信息):<<include>>

图书管理员 -->(图书归还)
(收罚款) .>(图书归还):<<extend>>
图书管理员 -->(图书借出)
图书管理员 ->(处理预约)
(处理预约).>(图书借出):<<extend>>
(图书借出)..>(检测读者账户):<<include>>

读者-->(借阅图书)
读者-->(查询图书)
读者-->(预约图书)
读者-->(登录系统)
读者-->(查询记录)
读者-->(归还图书)

(借阅图书)..>(查询图书):<<include>>
(借阅图书)..>(登录系统):<<include>>
(预约图书)..>(查询图书):<<include>>
(预约图书)..>(登录系统):<<include>>
(查询记录)..>(登录系统):<<include>>
(归还图书)..>(登录系统):<<include>>
(归还图书)..>(缴纳罚款):<<extend>>

系统管理员 ->图书管理员:<<generalization>>
@enduml