@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #Black
skinparam titleFontSize 24
Title setPassword

actor setPassword页面
actor API服务
database 数据库存储

== 修改密码页面 ==
数据库存储->数据库存储:预存了每个用户的信息：\n用户名+hash加密的密码
API服务->API服务:服务程序启动，生成公钥和私钥
setPassword页面->API服务:页面事件：mounted()，\nAPI请求:<b>get_public_key_str<b>，获取公钥
API服务->setPassword页面:返回公钥：public_key_str
setPassword页面->setPassword页面:用户输入用户名和原密码，点击确定按钮
setPassword页面->setPassword页面:检测输入的信息是否正确
setPassword页面->setPassword页面:使用JSEncrypt通过公钥加密输入的新密码
setPassword页面->API服务:API请求:<b>setPassword</b>,参数是用户名和公钥加密密码
API服务->API服务:使用RSA根据私钥解密收到的加密密码，得到用户密码
API服务->数据库存储:更新密码到数据库
数据库存储->API服务:返回该用户的hash密码
API服务->API服务:调用check_password_hash(hash密码,用户密码)
API服务->setPassword页面:返回成功信息
== 用户修改密码成功后，跳转到登录页面，清除Cookie==
@enduml